# TCL File Generated by Component Editor 18.1
# Thu Dec 31 19:34:33 PST 2020
# DO NOT MODIFY


# 
# bit_pix_bram_mod "bit_pix_bram_mod" v1.0
#  2020.12.31.19:34:33
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module bit_pix_bram_mod
# 
set_module_property DESCRIPTION ""
set_module_property NAME bit_pix_bram_mod
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME bit_pix_bram_mod
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL block_match_ram_module
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file block_match_ram_module.sv SYSTEM_VERILOG PATH block_matching/block_match_ram_module.sv
add_fileset_file bit_pix_bram.v VERILOG PATH block_matching/bit_pix_bram.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL block_match_ram_module
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bit_pix_bram.v VERILOG PATH block_matching/bit_pix_bram.v
add_fileset_file block_match_ram_module.sv SYSTEM_VERILOG PATH block_matching/block_match_ram_module.sv


# 
# parameters
# 
add_parameter third_width INTEGER 240
set_parameter_property third_width DEFAULT_VALUE 240
set_parameter_property third_width DISPLAY_NAME third_width
set_parameter_property third_width TYPE INTEGER
set_parameter_property third_width UNITS None
set_parameter_property third_width HDL_PARAMETER true
add_parameter third_height INTEGER 480
set_parameter_property third_height DEFAULT_VALUE 480
set_parameter_property third_height DISPLAY_NAME third_height
set_parameter_property third_height TYPE INTEGER
set_parameter_property third_height UNITS None
set_parameter_property third_height HDL_PARAMETER true
add_parameter center_width INTEGER 304
set_parameter_property center_width DEFAULT_VALUE 304
set_parameter_property center_width DISPLAY_NAME center_width
set_parameter_property center_width TYPE INTEGER
set_parameter_property center_width UNITS None
set_parameter_property center_width HDL_PARAMETER true
add_parameter rd_width INTEGER 8
set_parameter_property rd_width DEFAULT_VALUE 8
set_parameter_property rd_width DISPLAY_NAME rd_width
set_parameter_property rd_width TYPE INTEGER
set_parameter_property rd_width UNITS None
set_parameter_property rd_width HDL_PARAMETER true
add_parameter wr_width INTEGER 16
set_parameter_property wr_width DEFAULT_VALUE 16
set_parameter_property wr_width DISPLAY_NAME wr_width
set_parameter_property wr_width TYPE INTEGER
set_parameter_property wr_width UNITS None
set_parameter_property wr_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point wr
# 
add_interface wr conduit end
set_interface_property wr associatedClock clock
set_interface_property wr associatedReset reset
set_interface_property wr ENABLED true
set_interface_property wr EXPORT_OF ""
set_interface_property wr PORT_NAME_MAP ""
set_interface_property wr CMSIS_SVD_VARIABLES ""
set_interface_property wr SVD_ADDRESS_GROUP ""

add_interface_port wr wr_address address Input 16
add_interface_port wr wr_data writedata Input wr_width
add_interface_port wr write write Input 1
add_interface_port wr wr_third third Input 2


# 
# connection point left_rd
# 
add_interface left_rd conduit end
set_interface_property left_rd associatedClock clock
set_interface_property left_rd associatedReset reset
set_interface_property left_rd ENABLED true
set_interface_property left_rd EXPORT_OF ""
set_interface_property left_rd PORT_NAME_MAP ""
set_interface_property left_rd CMSIS_SVD_VARIABLES ""
set_interface_property left_rd SVD_ADDRESS_GROUP ""

add_interface_port left_rd rd_address_left address Input 16
add_interface_port left_rd rd_data_left readdata Output rd_width


# 
# connection point right_rd
# 
add_interface right_rd conduit end
set_interface_property right_rd associatedClock clock
set_interface_property right_rd associatedReset reset
set_interface_property right_rd ENABLED true
set_interface_property right_rd EXPORT_OF ""
set_interface_property right_rd PORT_NAME_MAP ""
set_interface_property right_rd CMSIS_SVD_VARIABLES ""
set_interface_property right_rd SVD_ADDRESS_GROUP ""

add_interface_port right_rd rd_address_right address Input 16
add_interface_port right_rd rd_data_right readdata Output rd_width


# 
# connection point centerleft_rd
# 
add_interface centerleft_rd conduit end
set_interface_property centerleft_rd associatedClock clock
set_interface_property centerleft_rd associatedReset reset
set_interface_property centerleft_rd ENABLED true
set_interface_property centerleft_rd EXPORT_OF ""
set_interface_property centerleft_rd PORT_NAME_MAP ""
set_interface_property centerleft_rd CMSIS_SVD_VARIABLES ""
set_interface_property centerleft_rd SVD_ADDRESS_GROUP ""

add_interface_port centerleft_rd rd_data_centerleft readdata Output rd_width
add_interface_port centerleft_rd rd_address_centerleft address Input 16


# 
# connection point centerright_rd
# 
add_interface centerright_rd conduit end
set_interface_property centerright_rd associatedClock clock
set_interface_property centerright_rd associatedReset reset
set_interface_property centerright_rd ENABLED true
set_interface_property centerright_rd EXPORT_OF ""
set_interface_property centerright_rd PORT_NAME_MAP ""
set_interface_property centerright_rd CMSIS_SVD_VARIABLES ""
set_interface_property centerright_rd SVD_ADDRESS_GROUP ""

add_interface_port centerright_rd rd_data_centerright readdata Output rd_width
add_interface_port centerright_rd rd_address_centerright address Input 16

