# TCL File Generated by Component Editor 18.1
# Thu Dec 24 10:27:24 PST 2020
# DO NOT MODIFY


# 
# blk_match_new "blk_match_new" v1.0
#  2020.12.24.10:27:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module blk_match_new
# 
set_module_property DESCRIPTION ""
set_module_property NAME blk_match_new
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME blk_match_new
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL block_match_new
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file block_match_new.sv SYSTEM_VERILOG PATH block_matching/block_match_new.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL block_match_new
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file block_match_new.sv SYSTEM_VERILOG PATH block_matching/block_match_new.sv


# 
# parameters
# 
add_parameter rd_port_w INTEGER 8
set_parameter_property rd_port_w DEFAULT_VALUE 8
set_parameter_property rd_port_w DISPLAY_NAME rd_port_w
set_parameter_property rd_port_w TYPE INTEGER
set_parameter_property rd_port_w UNITS None
set_parameter_property rd_port_w ALLOWED_RANGES -2147483648:2147483647
set_parameter_property rd_port_w HDL_PARAMETER true
add_parameter block_width INTEGER 16
set_parameter_property block_width DEFAULT_VALUE 16
set_parameter_property block_width DISPLAY_NAME block_width
set_parameter_property block_width TYPE INTEGER
set_parameter_property block_width UNITS None
set_parameter_property block_width HDL_PARAMETER true
add_parameter block_height INTEGER 16
set_parameter_property block_height DEFAULT_VALUE 16
set_parameter_property block_height DISPLAY_NAME block_height
set_parameter_property block_height TYPE INTEGER
set_parameter_property block_height UNITS None
set_parameter_property block_height HDL_PARAMETER true
add_parameter search_blk_w INTEGER 64
set_parameter_property search_blk_w DEFAULT_VALUE 64
set_parameter_property search_blk_w DISPLAY_NAME search_blk_w
set_parameter_property search_blk_w TYPE INTEGER
set_parameter_property search_blk_w UNITS None
set_parameter_property search_blk_w ALLOWED_RANGES -2147483648:2147483647
set_parameter_property search_blk_w HDL_PARAMETER true
add_parameter search_blk_h INTEGER 16
set_parameter_property search_blk_h DEFAULT_VALUE 16
set_parameter_property search_blk_h DISPLAY_NAME search_blk_h
set_parameter_property search_blk_h TYPE INTEGER
set_parameter_property search_blk_h UNITS None
set_parameter_property search_blk_h ALLOWED_RANGES -2147483648:2147483647
set_parameter_property search_blk_h HDL_PARAMETER true
add_parameter line_w INTEGER 128
set_parameter_property line_w DEFAULT_VALUE 128
set_parameter_property line_w DISPLAY_NAME line_w
set_parameter_property line_w TYPE INTEGER
set_parameter_property line_w UNITS None
set_parameter_property line_w ALLOWED_RANGES -2147483648:2147483647
set_parameter_property line_w HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges BOTH
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point ctrl_conduit
# 
add_interface ctrl_conduit conduit end
set_interface_property ctrl_conduit associatedClock clock
set_interface_property ctrl_conduit associatedReset reset
set_interface_property ctrl_conduit ENABLED true
set_interface_property ctrl_conduit EXPORT_OF ""
set_interface_property ctrl_conduit PORT_NAME_MAP ""
set_interface_property ctrl_conduit CMSIS_SVD_VARIABLES ""
set_interface_property ctrl_conduit SVD_ADDRESS_GROUP ""

add_interface_port ctrl_conduit blk_index blk_index Input 16
add_interface_port ctrl_conduit start start Input 1
add_interface_port ctrl_conduit done done Output 1
add_interface_port ctrl_conduit blk_start_address blk_addr Input 16
add_interface_port ctrl_conduit srch_start_address srch_addr Input 16


# 
# connection point result_conduit
# 
add_interface result_conduit conduit end
set_interface_property result_conduit associatedClock clock
set_interface_property result_conduit associatedReset reset
set_interface_property result_conduit ENABLED true
set_interface_property result_conduit EXPORT_OF ""
set_interface_property result_conduit PORT_NAME_MAP ""
set_interface_property result_conduit CMSIS_SVD_VARIABLES ""
set_interface_property result_conduit SVD_ADDRESS_GROUP ""

add_interface_port result_conduit blk_block blk_block Output block_width*block_height
add_interface_port result_conduit blk_index_o blk_index Output 16
add_interface_port result_conduit srch_block srch_block Output block_width*block_height
add_interface_port result_conduit coords_out coords_out Output 16
add_interface_port result_conduit blks_valid blks_valid Output 1


# 
# connection point srch_master
# 
add_interface srch_master conduit end
set_interface_property srch_master associatedClock clock
set_interface_property srch_master associatedReset reset
set_interface_property srch_master ENABLED true
set_interface_property srch_master EXPORT_OF ""
set_interface_property srch_master PORT_NAME_MAP ""
set_interface_property srch_master CMSIS_SVD_VARIABLES ""
set_interface_property srch_master SVD_ADDRESS_GROUP ""

add_interface_port srch_master srch_rd_addr address Output 16
add_interface_port srch_master srch_rd_data readdata Input rd_port_w


# 
# connection point blk_master
# 
add_interface blk_master conduit end
set_interface_property blk_master associatedClock clock
set_interface_property blk_master associatedReset reset
set_interface_property blk_master ENABLED true
set_interface_property blk_master EXPORT_OF ""
set_interface_property blk_master PORT_NAME_MAP ""
set_interface_property blk_master CMSIS_SVD_VARIABLES ""
set_interface_property blk_master SVD_ADDRESS_GROUP ""

add_interface_port blk_master blk_rd_addr address Output 16
add_interface_port blk_master blk_rd_data readdata Input rd_port_w

