# TCL File Generated by Component Editor 18.1
# Thu Nov 12 21:48:01 PST 2020
# DO NOT MODIFY


# 
# ddr3_reader_vertical "ddr3_reader_vertical" v1.0
#  2020.11.12.21:48:01
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ddr3_reader_vertical
# 
set_module_property DESCRIPTION ""
set_module_property NAME ddr3_reader_vertical
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ddr3_reader_vertical
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ddr3_reader_grayfilter_short
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ddr3_reader_grayfilter_short.sv SYSTEM_VERILOG PATH block_matching/ddr3_reader_grayfilter_short.sv
add_fileset_file ddr3reader_dcfifo.v VERILOG PATH ddr3reader_dcfifo.v
add_fileset_file gray_info_fifo.v VERILOG PATH gray_info_fifo.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ddr3_reader_grayfilter_short
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file ddr3_reader_grayfilter_short.sv SYSTEM_VERILOG PATH block_matching/ddr3_reader_grayfilter_short.sv
add_fileset_file ddr3reader_dcfifo.v VERILOG PATH ddr3reader_dcfifo.v
add_fileset_file gray_info_fifo.v VERILOG PATH gray_info_fifo.v


# 
# parameters
# 
add_parameter in_width INTEGER 16
set_parameter_property in_width DEFAULT_VALUE 16
set_parameter_property in_width DISPLAY_NAME in_width
set_parameter_property in_width TYPE INTEGER
set_parameter_property in_width ENABLED false
set_parameter_property in_width UNITS None
set_parameter_property in_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property in_width HDL_PARAMETER true
add_parameter frame_third_width INTEGER 240
set_parameter_property frame_third_width DEFAULT_VALUE 240
set_parameter_property frame_third_width DISPLAY_NAME frame_third_width
set_parameter_property frame_third_width TYPE INTEGER
set_parameter_property frame_third_width UNITS None
set_parameter_property frame_third_width HDL_PARAMETER true
add_parameter frame_lines INTEGER 240
set_parameter_property frame_lines DEFAULT_VALUE 240
set_parameter_property frame_lines DISPLAY_NAME frame_lines
set_parameter_property frame_lines TYPE INTEGER
set_parameter_property frame_lines UNITS None
set_parameter_property frame_lines ALLOWED_RANGES -2147483648:2147483647
set_parameter_property frame_lines HDL_PARAMETER true
add_parameter frame_full_width INTEGER 768
set_parameter_property frame_full_width DEFAULT_VALUE 768
set_parameter_property frame_full_width DISPLAY_NAME frame_full_width
set_parameter_property frame_full_width TYPE INTEGER
set_parameter_property frame_full_width UNITS None
set_parameter_property frame_full_width HDL_PARAMETER true
add_parameter burst_len INTEGER 1
set_parameter_property burst_len DEFAULT_VALUE 1
set_parameter_property burst_len DISPLAY_NAME burst_len
set_parameter_property burst_len TYPE INTEGER
set_parameter_property burst_len ENABLED false
set_parameter_property burst_len UNITS None
set_parameter_property burst_len ALLOWED_RANGES -2147483648:2147483647
set_parameter_property burst_len HDL_PARAMETER true


# 
# display items
# 


# 
# connection point ddr3clk_reset
# 
add_interface ddr3clk_reset reset end
set_interface_property ddr3clk_reset associatedClock ddr3clk_sink
set_interface_property ddr3clk_reset synchronousEdges DEASSERT
set_interface_property ddr3clk_reset ENABLED true
set_interface_property ddr3clk_reset EXPORT_OF ""
set_interface_property ddr3clk_reset PORT_NAME_MAP ""
set_interface_property ddr3clk_reset CMSIS_SVD_VARIABLES ""
set_interface_property ddr3clk_reset SVD_ADDRESS_GROUP ""

add_interface_port ddr3clk_reset ddr3clk_reset reset Input 1


# 
# connection point pclk_reset
# 
add_interface pclk_reset reset end
set_interface_property pclk_reset associatedClock pclk_sink
set_interface_property pclk_reset synchronousEdges DEASSERT
set_interface_property pclk_reset ENABLED true
set_interface_property pclk_reset EXPORT_OF ""
set_interface_property pclk_reset PORT_NAME_MAP ""
set_interface_property pclk_reset CMSIS_SVD_VARIABLES ""
set_interface_property pclk_reset SVD_ADDRESS_GROUP ""

add_interface_port pclk_reset pclk_reset reset Input 1


# 
# connection point pixel_source
# 
add_interface pixel_source avalon_streaming start
set_interface_property pixel_source associatedClock pclk_sink
set_interface_property pixel_source associatedReset pclk_reset
set_interface_property pixel_source dataBitsPerSymbol 264
set_interface_property pixel_source errorDescriptor ""
set_interface_property pixel_source firstSymbolInHighOrderBits true
set_interface_property pixel_source maxChannel 0
set_interface_property pixel_source readyLatency 0
set_interface_property pixel_source ENABLED true
set_interface_property pixel_source EXPORT_OF ""
set_interface_property pixel_source PORT_NAME_MAP ""
set_interface_property pixel_source CMSIS_SVD_VARIABLES ""
set_interface_property pixel_source SVD_ADDRESS_GROUP ""

add_interface_port pixel_source pixel_data data Output 264
add_interface_port pixel_source pixel_valid valid Output 1


# 
# connection point fifo_almost_full_sink
# 
add_interface fifo_almost_full_sink avalon_streaming end
set_interface_property fifo_almost_full_sink associatedClock pclk_sink
set_interface_property fifo_almost_full_sink associatedReset pclk_reset
set_interface_property fifo_almost_full_sink dataBitsPerSymbol 1
set_interface_property fifo_almost_full_sink errorDescriptor ""
set_interface_property fifo_almost_full_sink firstSymbolInHighOrderBits true
set_interface_property fifo_almost_full_sink maxChannel 0
set_interface_property fifo_almost_full_sink readyLatency 0
set_interface_property fifo_almost_full_sink ENABLED true
set_interface_property fifo_almost_full_sink EXPORT_OF ""
set_interface_property fifo_almost_full_sink PORT_NAME_MAP ""
set_interface_property fifo_almost_full_sink CMSIS_SVD_VARIABLES ""
set_interface_property fifo_almost_full_sink SVD_ADDRESS_GROUP ""

add_interface_port fifo_almost_full_sink pix_fifo_almost_full data Input 1


# 
# connection point start_addr_sink
# 
add_interface start_addr_sink avalon_streaming end
set_interface_property start_addr_sink associatedClock ddr3clk_sink
set_interface_property start_addr_sink associatedReset ddr3clk_reset
set_interface_property start_addr_sink dataBitsPerSymbol 29
set_interface_property start_addr_sink errorDescriptor ""
set_interface_property start_addr_sink firstSymbolInHighOrderBits true
set_interface_property start_addr_sink maxChannel 0
set_interface_property start_addr_sink readyLatency 0
set_interface_property start_addr_sink ENABLED true
set_interface_property start_addr_sink EXPORT_OF ""
set_interface_property start_addr_sink PORT_NAME_MAP ""
set_interface_property start_addr_sink CMSIS_SVD_VARIABLES ""
set_interface_property start_addr_sink SVD_ADDRESS_GROUP ""

add_interface_port start_addr_sink start_ready ready Output 1
add_interface_port start_addr_sink start_valid valid Input 1
add_interface_port start_addr_sink start_data data Input 29


# 
# connection point ddr3_read_master
# 
add_interface ddr3_read_master avalon start
set_interface_property ddr3_read_master addressUnits WORDS
set_interface_property ddr3_read_master associatedClock ddr3clk_sink
set_interface_property ddr3_read_master associatedReset ddr3clk_reset
set_interface_property ddr3_read_master bitsPerSymbol 8
set_interface_property ddr3_read_master burstOnBurstBoundariesOnly false
set_interface_property ddr3_read_master burstcountUnits WORDS
set_interface_property ddr3_read_master doStreamReads false
set_interface_property ddr3_read_master doStreamWrites false
set_interface_property ddr3_read_master holdTime 0
set_interface_property ddr3_read_master linewrapBursts false
set_interface_property ddr3_read_master maximumPendingReadTransactions 0
set_interface_property ddr3_read_master maximumPendingWriteTransactions 0
set_interface_property ddr3_read_master readLatency 0
set_interface_property ddr3_read_master readWaitTime 1
set_interface_property ddr3_read_master setupTime 0
set_interface_property ddr3_read_master timingUnits Cycles
set_interface_property ddr3_read_master writeWaitTime 0
set_interface_property ddr3_read_master ENABLED true
set_interface_property ddr3_read_master EXPORT_OF ""
set_interface_property ddr3_read_master PORT_NAME_MAP ""
set_interface_property ddr3_read_master CMSIS_SVD_VARIABLES ""
set_interface_property ddr3_read_master SVD_ADDRESS_GROUP ""

add_interface_port ddr3_read_master ddr3_address address Output 27
add_interface_port ddr3_read_master ddr3_readdata readdata Input 256
add_interface_port ddr3_read_master ddr3_read read Output 1
add_interface_port ddr3_read_master ddr3_waitrequest waitrequest Input 1
add_interface_port ddr3_read_master ddr3_readdatavalid readdatavalid Input 1
add_interface_port ddr3_read_master ddr3_burstcount burstcount Output 4


# 
# connection point pclk_sink
# 
add_interface pclk_sink clock end
set_interface_property pclk_sink clockRate 0
set_interface_property pclk_sink ENABLED true
set_interface_property pclk_sink EXPORT_OF ""
set_interface_property pclk_sink PORT_NAME_MAP ""
set_interface_property pclk_sink CMSIS_SVD_VARIABLES ""
set_interface_property pclk_sink SVD_ADDRESS_GROUP ""

add_interface_port pclk_sink pclk clk Input 1


# 
# connection point ddr3clk_sink
# 
add_interface ddr3clk_sink clock end
set_interface_property ddr3clk_sink clockRate 0
set_interface_property ddr3clk_sink ENABLED true
set_interface_property ddr3clk_sink EXPORT_OF ""
set_interface_property ddr3clk_sink PORT_NAME_MAP ""
set_interface_property ddr3clk_sink CMSIS_SVD_VARIABLES ""
set_interface_property ddr3clk_sink SVD_ADDRESS_GROUP ""

add_interface_port ddr3clk_sink ddr3clk clk Input 1

