# TCL File Generated by Component Editor 18.1
# Sun Feb 07 17:41:40 PST 2021
# DO NOT MODIFY


# 
# ddr3_reader_gray_crop "ddr3_reader_gray_crop" v1.0
#  2021.02.07.17:41:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ddr3_reader_gray_crop
# 
set_module_property DESCRIPTION ""
set_module_property NAME ddr3_reader_gray_crop
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ddr3_reader_gray_crop
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ddr3_reader_grayscale_crop
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ddr3_reader_grayscale_crop.sv SYSTEM_VERILOG PATH disparity_filtering/ddr3_reader_grayscale_crop.sv TOP_LEVEL_FILE
add_fileset_file ddr3reader_dcfifo_showahead.v VERILOG PATH disparity_filtering/ddr3reader_dcfifo_showahead.v


# 
# parameters
# 
add_parameter frame_width INTEGER 768
set_parameter_property frame_width DEFAULT_VALUE 768
set_parameter_property frame_width DISPLAY_NAME frame_width
set_parameter_property frame_width TYPE INTEGER
set_parameter_property frame_width UNITS None
set_parameter_property frame_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property frame_width HDL_PARAMETER true
add_parameter crop_width INTEGER 240
set_parameter_property crop_width DEFAULT_VALUE 240
set_parameter_property crop_width DISPLAY_NAME crop_width
set_parameter_property crop_width TYPE INTEGER
set_parameter_property crop_width UNITS None
set_parameter_property crop_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property crop_width HDL_PARAMETER true
add_parameter frame_lines INTEGER 480
set_parameter_property frame_lines DEFAULT_VALUE 480
set_parameter_property frame_lines DISPLAY_NAME frame_lines
set_parameter_property frame_lines TYPE INTEGER
set_parameter_property frame_lines UNITS None
set_parameter_property frame_lines ALLOWED_RANGES -2147483648:2147483647
set_parameter_property frame_lines HDL_PARAMETER true
add_parameter i_am_left INTEGER 1
set_parameter_property i_am_left DEFAULT_VALUE 1
set_parameter_property i_am_left DISPLAY_NAME i_am_left
set_parameter_property i_am_left TYPE INTEGER
set_parameter_property i_am_left UNITS None
set_parameter_property i_am_left ALLOWED_RANGES -2147483648:2147483647
set_parameter_property i_am_left HDL_PARAMETER true
add_parameter decimate_factor INTEGER 2
set_parameter_property decimate_factor DEFAULT_VALUE 2
set_parameter_property decimate_factor DISPLAY_NAME decimate_factor
set_parameter_property decimate_factor TYPE INTEGER
set_parameter_property decimate_factor UNITS None
set_parameter_property decimate_factor HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock pclk_sink
set_interface_property avalon_streaming_source associatedReset pclk_reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source pixel_data data Output 8
add_interface_port avalon_streaming_source pixel_ready ready Input 1
add_interface_port avalon_streaming_source pixel_valid valid Output 1


# 
# connection point pclk_sink
# 
add_interface pclk_sink clock end
set_interface_property pclk_sink clockRate 0
set_interface_property pclk_sink ENABLED true
set_interface_property pclk_sink EXPORT_OF ""
set_interface_property pclk_sink PORT_NAME_MAP ""
set_interface_property pclk_sink CMSIS_SVD_VARIABLES ""
set_interface_property pclk_sink SVD_ADDRESS_GROUP ""

add_interface_port pclk_sink pclk clk Input 1


# 
# connection point ddr3clk_reset
# 
add_interface ddr3clk_reset reset end
set_interface_property ddr3clk_reset associatedClock ddr3clk_sink
set_interface_property ddr3clk_reset synchronousEdges DEASSERT
set_interface_property ddr3clk_reset ENABLED true
set_interface_property ddr3clk_reset EXPORT_OF ""
set_interface_property ddr3clk_reset PORT_NAME_MAP ""
set_interface_property ddr3clk_reset CMSIS_SVD_VARIABLES ""
set_interface_property ddr3clk_reset SVD_ADDRESS_GROUP ""

add_interface_port ddr3clk_reset ddr3clk_reset reset Input 1


# 
# connection point ddr3clk_sink
# 
add_interface ddr3clk_sink clock end
set_interface_property ddr3clk_sink clockRate 0
set_interface_property ddr3clk_sink ENABLED true
set_interface_property ddr3clk_sink EXPORT_OF ""
set_interface_property ddr3clk_sink PORT_NAME_MAP ""
set_interface_property ddr3clk_sink CMSIS_SVD_VARIABLES ""
set_interface_property ddr3clk_sink SVD_ADDRESS_GROUP ""

add_interface_port ddr3clk_sink ddr3clk clk Input 1


# 
# connection point address_data_sink
# 
add_interface address_data_sink avalon_streaming end
set_interface_property address_data_sink associatedClock ddr3clk_sink
set_interface_property address_data_sink associatedReset ddr3clk_reset
set_interface_property address_data_sink dataBitsPerSymbol 29
set_interface_property address_data_sink errorDescriptor ""
set_interface_property address_data_sink firstSymbolInHighOrderBits true
set_interface_property address_data_sink maxChannel 0
set_interface_property address_data_sink readyLatency 0
set_interface_property address_data_sink ENABLED true
set_interface_property address_data_sink EXPORT_OF ""
set_interface_property address_data_sink PORT_NAME_MAP ""
set_interface_property address_data_sink CMSIS_SVD_VARIABLES ""
set_interface_property address_data_sink SVD_ADDRESS_GROUP ""

add_interface_port address_data_sink address_in_data data Input 29
add_interface_port address_data_sink address_in_valid valid Input 1


# 
# connection point ddr3_master
# 
add_interface ddr3_master avalon start
set_interface_property ddr3_master addressUnits WORDS
set_interface_property ddr3_master associatedClock ddr3clk_sink
set_interface_property ddr3_master associatedReset ddr3clk_reset
set_interface_property ddr3_master bitsPerSymbol 8
set_interface_property ddr3_master burstOnBurstBoundariesOnly false
set_interface_property ddr3_master burstcountUnits WORDS
set_interface_property ddr3_master doStreamReads false
set_interface_property ddr3_master doStreamWrites false
set_interface_property ddr3_master holdTime 0
set_interface_property ddr3_master linewrapBursts false
set_interface_property ddr3_master maximumPendingReadTransactions 0
set_interface_property ddr3_master maximumPendingWriteTransactions 0
set_interface_property ddr3_master readLatency 0
set_interface_property ddr3_master readWaitTime 1
set_interface_property ddr3_master setupTime 0
set_interface_property ddr3_master timingUnits Cycles
set_interface_property ddr3_master writeWaitTime 0
set_interface_property ddr3_master ENABLED true
set_interface_property ddr3_master EXPORT_OF ""
set_interface_property ddr3_master PORT_NAME_MAP ""
set_interface_property ddr3_master CMSIS_SVD_VARIABLES ""
set_interface_property ddr3_master SVD_ADDRESS_GROUP ""

add_interface_port ddr3_master ddr3_address address Output 27
add_interface_port ddr3_master ddr3_readdata readdata Input 256
add_interface_port ddr3_master ddr3_read read Output 1
add_interface_port ddr3_master ddr3_waitrequest waitrequest Input 1
add_interface_port ddr3_master ddr3_readdatavalid readdatavalid Input 1
add_interface_port ddr3_master ddr3_burstcount burstcount Output 5


# 
# connection point pclk_reset
# 
add_interface pclk_reset reset end
set_interface_property pclk_reset associatedClock pclk_sink
set_interface_property pclk_reset synchronousEdges DEASSERT
set_interface_property pclk_reset ENABLED true
set_interface_property pclk_reset EXPORT_OF ""
set_interface_property pclk_reset PORT_NAME_MAP ""
set_interface_property pclk_reset CMSIS_SVD_VARIABLES ""
set_interface_property pclk_reset SVD_ADDRESS_GROUP ""

add_interface_port pclk_reset pclk_reset reset Input 1

