# TCL File Generated by Component Editor 18.1
# Wed Dec 16 20:34:19 PST 2020
# DO NOT MODIFY


# 
# ddr3_writer_supersimple "ddr3_writer_ss" v1.0
#  2020.12.16.20:34:19
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ddr3_writer_supersimple
# 
set_module_property DESCRIPTION ""
set_module_property NAME ddr3_writer_supersimple
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ddr3_writer_ss
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ddr3_pixel_writer_supersimple
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ddr3_pixel_writer_supersimple.sv SYSTEM_VERILOG PATH ddr3_pixel_writer_supersimple.sv
add_fileset_file ddr3_writer_fifo.v VERILOG PATH gray_in/ddr3_writer_fifo.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ddr3_pixel_writer_supersimple
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ddr3_pixel_writer_supersimple.sv SYSTEM_VERILOG PATH ddr3_pixel_writer_supersimple.sv
add_fileset_file ddr3_writer_fifo.v VERILOG PATH gray_in/ddr3_writer_fifo.v


# 
# parameters
# 
add_parameter in_width INTEGER 64 ""
set_parameter_property in_width DEFAULT_VALUE 64
set_parameter_property in_width DISPLAY_NAME in_width
set_parameter_property in_width TYPE INTEGER
set_parameter_property in_width UNITS None
set_parameter_property in_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property in_width DESCRIPTION ""
set_parameter_property in_width HDL_PARAMETER true
add_parameter burst_len INTEGER 8
set_parameter_property burst_len DEFAULT_VALUE 8
set_parameter_property burst_len DISPLAY_NAME burst_len
set_parameter_property burst_len TYPE INTEGER
set_parameter_property burst_len UNITS None
set_parameter_property burst_len ALLOWED_RANGES -2147483648:2147483647
set_parameter_property burst_len HDL_PARAMETER true
add_parameter num_pixels INTEGER 2764800
set_parameter_property num_pixels DEFAULT_VALUE 2764800
set_parameter_property num_pixels DISPLAY_NAME num_pixels
set_parameter_property num_pixels TYPE INTEGER
set_parameter_property num_pixels UNITS None
set_parameter_property num_pixels ALLOWED_RANGES -2147483648:2147483647
set_parameter_property num_pixels HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits WORDS
set_interface_property avalon_master associatedClock ddr3clk
set_interface_property avalon_master associatedReset ddr3clk_reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master ddr3_burstcount burstcount Output 8
add_interface_port avalon_master ddr3_waitrequest waitrequest Input 1
add_interface_port avalon_master ddr3_write write Output 1
add_interface_port avalon_master ddr3_write_address address Output 27
add_interface_port avalon_master ddr3_write_data writedata Output 256


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock pclk
set_interface_property avalon_streaming_sink associatedReset pclk_reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 16
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink pixel data Input 16
add_interface_port avalon_streaming_sink pixel_valid valid Input 1
add_interface_port avalon_streaming_sink pixel_ready ready Output 1


# 
# connection point ddr3clk
# 
add_interface ddr3clk clock end
set_interface_property ddr3clk clockRate 0
set_interface_property ddr3clk ENABLED true
set_interface_property ddr3clk EXPORT_OF ""
set_interface_property ddr3clk PORT_NAME_MAP ""
set_interface_property ddr3clk CMSIS_SVD_VARIABLES ""
set_interface_property ddr3clk SVD_ADDRESS_GROUP ""

add_interface_port ddr3clk ddr3_clk clk Input 1


# 
# connection point pclk_reset
# 
add_interface pclk_reset reset end
set_interface_property pclk_reset associatedClock pclk
set_interface_property pclk_reset synchronousEdges DEASSERT
set_interface_property pclk_reset ENABLED true
set_interface_property pclk_reset EXPORT_OF ""
set_interface_property pclk_reset PORT_NAME_MAP ""
set_interface_property pclk_reset CMSIS_SVD_VARIABLES ""
set_interface_property pclk_reset SVD_ADDRESS_GROUP ""

add_interface_port pclk_reset pclk_reset reset Input 1


# 
# connection point ddr3clk_reset
# 
add_interface ddr3clk_reset reset end
set_interface_property ddr3clk_reset associatedClock ddr3clk
set_interface_property ddr3clk_reset synchronousEdges DEASSERT
set_interface_property ddr3clk_reset ENABLED true
set_interface_property ddr3clk_reset EXPORT_OF ""
set_interface_property ddr3clk_reset PORT_NAME_MAP ""
set_interface_property ddr3clk_reset CMSIS_SVD_VARIABLES ""
set_interface_property ddr3clk_reset SVD_ADDRESS_GROUP ""

add_interface_port ddr3clk_reset ddr3_clk_reset reset Input 1


# 
# connection point pclk
# 
add_interface pclk clock end
set_interface_property pclk clockRate 0
set_interface_property pclk ENABLED true
set_interface_property pclk EXPORT_OF ""
set_interface_property pclk PORT_NAME_MAP ""
set_interface_property pclk CMSIS_SVD_VARIABLES ""
set_interface_property pclk SVD_ADDRESS_GROUP ""

add_interface_port pclk pclk clk Input 1


# 
# connection point fifo_level_source
# 
add_interface fifo_level_source avalon_streaming start
set_interface_property fifo_level_source associatedClock pclk
set_interface_property fifo_level_source associatedReset pclk_reset
set_interface_property fifo_level_source dataBitsPerSymbol 8
set_interface_property fifo_level_source errorDescriptor ""
set_interface_property fifo_level_source firstSymbolInHighOrderBits true
set_interface_property fifo_level_source maxChannel 0
set_interface_property fifo_level_source readyLatency 0
set_interface_property fifo_level_source ENABLED true
set_interface_property fifo_level_source EXPORT_OF ""
set_interface_property fifo_level_source PORT_NAME_MAP ""
set_interface_property fifo_level_source CMSIS_SVD_VARIABLES ""
set_interface_property fifo_level_source SVD_ADDRESS_GROUP ""

add_interface_port fifo_level_source fifo_level data Output 8

