# TCL File Generated by Component Editor 18.1
# Thu May 02 18:18:39 PDT 2019
# DO NOT MODIFY


# 
# gray_receiver "gray_receiver" v1.0
#  2019.05.02.18:18:39
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module gray_receiver
# 
set_module_property DESCRIPTION ""
set_module_property NAME gray_receiver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME gray_receiver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gray_receiver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gray_receiver.sv SYSTEM_VERILOG PATH gray_in/gray_receiver.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter frame_width INTEGER 480
set_parameter_property frame_width DEFAULT_VALUE 480
set_parameter_property frame_width DISPLAY_NAME frame_width
set_parameter_property frame_width TYPE INTEGER
set_parameter_property frame_width UNITS None
set_parameter_property frame_width HDL_PARAMETER true
add_parameter frame_lines INTEGER 2880
set_parameter_property frame_lines DEFAULT_VALUE 2880
set_parameter_property frame_lines DISPLAY_NAME frame_lines
set_parameter_property frame_lines TYPE INTEGER
set_parameter_property frame_lines UNITS None
set_parameter_property frame_lines HDL_PARAMETER true


# 
# display items
# 


# 
# connection point pixel_sink
# 
add_interface pixel_sink avalon_streaming end
set_interface_property pixel_sink associatedClock pclk_sink
set_interface_property pixel_sink associatedReset pclk_reset_sink
set_interface_property pixel_sink dataBitsPerSymbol 8
set_interface_property pixel_sink errorDescriptor ""
set_interface_property pixel_sink firstSymbolInHighOrderBits true
set_interface_property pixel_sink maxChannel 0
set_interface_property pixel_sink readyLatency 0
set_interface_property pixel_sink ENABLED true
set_interface_property pixel_sink EXPORT_OF ""
set_interface_property pixel_sink PORT_NAME_MAP ""
set_interface_property pixel_sink CMSIS_SVD_VARIABLES ""
set_interface_property pixel_sink SVD_ADDRESS_GROUP ""

add_interface_port pixel_sink pixel_data data Input 8
add_interface_port pixel_sink pixel_valid valid Input 1


# 
# connection point pixel_source
# 
add_interface pixel_source avalon_streaming start
set_interface_property pixel_source associatedClock pclk_sink
set_interface_property pixel_source associatedReset pclk_reset_sink
set_interface_property pixel_source dataBitsPerSymbol 9
set_interface_property pixel_source errorDescriptor ""
set_interface_property pixel_source firstSymbolInHighOrderBits true
set_interface_property pixel_source maxChannel 0
set_interface_property pixel_source readyLatency 0
set_interface_property pixel_source ENABLED true
set_interface_property pixel_source EXPORT_OF ""
set_interface_property pixel_source PORT_NAME_MAP ""
set_interface_property pixel_source CMSIS_SVD_VARIABLES ""
set_interface_property pixel_source SVD_ADDRESS_GROUP ""

add_interface_port pixel_source pixel_out data Output 9
add_interface_port pixel_source pixel_out_valid valid Output 1


# 
# connection point pclk_sink
# 
add_interface pclk_sink clock end
set_interface_property pclk_sink clockRate 0
set_interface_property pclk_sink ENABLED true
set_interface_property pclk_sink EXPORT_OF ""
set_interface_property pclk_sink PORT_NAME_MAP ""
set_interface_property pclk_sink CMSIS_SVD_VARIABLES ""
set_interface_property pclk_sink SVD_ADDRESS_GROUP ""

add_interface_port pclk_sink pclk clk Input 1


# 
# connection point pclk_reset_sink
# 
add_interface pclk_reset_sink reset end
set_interface_property pclk_reset_sink associatedClock pclk_sink
set_interface_property pclk_reset_sink synchronousEdges DEASSERT
set_interface_property pclk_reset_sink ENABLED true
set_interface_property pclk_reset_sink EXPORT_OF ""
set_interface_property pclk_reset_sink PORT_NAME_MAP ""
set_interface_property pclk_reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property pclk_reset_sink SVD_ADDRESS_GROUP ""

add_interface_port pclk_reset_sink pclk_reset reset Input 1

