# TCL File Generated by Component Editor 18.1
# Fri Jul 05 15:18:10 PDT 2019
# DO NOT MODIFY


# 
# hamming_dist "hamming_dist" v1.0
#  2019.07.05.15:18:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hamming_dist
# 
set_module_property DESCRIPTION ""
set_module_property NAME hamming_dist
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME hamming_dist
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hamming_dist_new
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hamming_dist_new.sv SYSTEM_VERILOG PATH block_matching/hamming_dist_new.sv TOP_LEVEL_FILE
add_fileset_file pop_count.sv SYSTEM_VERILOG PATH block_matching/pop_count.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL hamming_dist_new
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hamming_dist_new.sv SYSTEM_VERILOG PATH block_matching/hamming_dist_new.sv
add_fileset_file pop_count.sv SYSTEM_VERILOG PATH block_matching/pop_count.sv


# 
# parameters
# 
add_parameter blk_size INTEGER 256
set_parameter_property blk_size DEFAULT_VALUE 256
set_parameter_property blk_size DISPLAY_NAME blk_size
set_parameter_property blk_size TYPE INTEGER
set_parameter_property blk_size UNITS None
set_parameter_property blk_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property blk_size HDL_PARAMETER true
add_parameter lut_bits_in INTEGER 4
set_parameter_property lut_bits_in DEFAULT_VALUE 4
set_parameter_property lut_bits_in DISPLAY_NAME lut_bits_in
set_parameter_property lut_bits_in TYPE INTEGER
set_parameter_property lut_bits_in UNITS None
set_parameter_property lut_bits_in ALLOWED_RANGES -2147483648:2147483647
set_parameter_property lut_bits_in HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges BOTH
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point out_conduit
# 
add_interface out_conduit conduit end
set_interface_property out_conduit associatedClock clock
set_interface_property out_conduit associatedReset reset
set_interface_property out_conduit ENABLED true
set_interface_property out_conduit EXPORT_OF ""
set_interface_property out_conduit PORT_NAME_MAP ""
set_interface_property out_conduit CMSIS_SVD_VARIABLES ""
set_interface_property out_conduit SVD_ADDRESS_GROUP ""

add_interface_port out_conduit blk_index_o blk_index Output 16
add_interface_port out_conduit sum_valid valid Output 1
add_interface_port out_conduit sum sum Output 8
add_interface_port out_conduit xors xors Output blk_size
add_interface_port out_conduit out_coords blk_coords Output 16


# 
# connection point in_conduit
# 
add_interface in_conduit conduit end
set_interface_property in_conduit associatedClock clock
set_interface_property in_conduit associatedReset reset
set_interface_property in_conduit ENABLED true
set_interface_property in_conduit EXPORT_OF ""
set_interface_property in_conduit PORT_NAME_MAP ""
set_interface_property in_conduit CMSIS_SVD_VARIABLES ""
set_interface_property in_conduit SVD_ADDRESS_GROUP ""

add_interface_port in_conduit right blk_block Input blk_size
add_interface_port in_conduit left srch_block Input blk_size
add_interface_port in_conduit blk_index_i blk_index Input 16
add_interface_port in_conduit blks_valid blks_valid Input 1
add_interface_port in_conduit in_coords coords_out Input 16

