# TCL File Generated by Component Editor 18.1
# Sun Nov 08 14:16:40 PST 2020
# DO NOT MODIFY


# 
# local_average_pad_v2 "local_average_pad_v2" v1.0
#  2020.11.08.14:16:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module local_average_pad_v2
# 
set_module_property DESCRIPTION ""
set_module_property NAME local_average_pad_v2
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME local_average_pad_v2
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL local_average_pad_v2
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file local_average_pad_v2.sv SYSTEM_VERILOG PATH gray_in/local_average_pad_v2.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter radius INTEGER 8
set_parameter_property radius DEFAULT_VALUE 8
set_parameter_property radius DISPLAY_NAME radius
set_parameter_property radius TYPE INTEGER
set_parameter_property radius UNITS None
set_parameter_property radius ALLOWED_RANGES -2147483648:2147483647
set_parameter_property radius HDL_PARAMETER true
add_parameter frame_width INTEGER 128
set_parameter_property frame_width DEFAULT_VALUE 128
set_parameter_property frame_width DISPLAY_NAME frame_width
set_parameter_property frame_width TYPE INTEGER
set_parameter_property frame_width UNITS None
set_parameter_property frame_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property frame_width HDL_PARAMETER true
add_parameter frame_lines INTEGER 480
set_parameter_property frame_lines DEFAULT_VALUE 480
set_parameter_property frame_lines DISPLAY_NAME frame_lines
set_parameter_property frame_lines TYPE INTEGER
set_parameter_property frame_lines UNITS None
set_parameter_property frame_lines ALLOWED_RANGES -2147483648:2147483647
set_parameter_property frame_lines HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point pixel_sink
# 
add_interface pixel_sink avalon_streaming end
set_interface_property pixel_sink associatedClock clock
set_interface_property pixel_sink associatedReset reset
set_interface_property pixel_sink dataBitsPerSymbol 9
set_interface_property pixel_sink errorDescriptor ""
set_interface_property pixel_sink firstSymbolInHighOrderBits true
set_interface_property pixel_sink maxChannel 0
set_interface_property pixel_sink readyLatency 0
set_interface_property pixel_sink ENABLED true
set_interface_property pixel_sink EXPORT_OF ""
set_interface_property pixel_sink PORT_NAME_MAP ""
set_interface_property pixel_sink CMSIS_SVD_VARIABLES ""
set_interface_property pixel_sink SVD_ADDRESS_GROUP ""

add_interface_port pixel_sink pixel data Input 9
add_interface_port pixel_sink pixel_valid valid Input 1


# 
# connection point local_avg_sink
# 
add_interface local_avg_sink avalon_streaming end
set_interface_property local_avg_sink associatedClock clock
set_interface_property local_avg_sink associatedReset reset
set_interface_property local_avg_sink dataBitsPerSymbol 8
set_interface_property local_avg_sink errorDescriptor ""
set_interface_property local_avg_sink firstSymbolInHighOrderBits true
set_interface_property local_avg_sink maxChannel 0
set_interface_property local_avg_sink readyLatency 0
set_interface_property local_avg_sink ENABLED true
set_interface_property local_avg_sink EXPORT_OF ""
set_interface_property local_avg_sink PORT_NAME_MAP ""
set_interface_property local_avg_sink CMSIS_SVD_VARIABLES ""
set_interface_property local_avg_sink SVD_ADDRESS_GROUP ""

add_interface_port local_avg_sink local_average data Input 8
add_interface_port local_avg_sink local_average_valid valid Input 1


# 
# connection point pixel_source
# 
add_interface pixel_source avalon_streaming start
set_interface_property pixel_source associatedClock clock
set_interface_property pixel_source associatedReset reset
set_interface_property pixel_source dataBitsPerSymbol 17
set_interface_property pixel_source errorDescriptor ""
set_interface_property pixel_source firstSymbolInHighOrderBits true
set_interface_property pixel_source maxChannel 0
set_interface_property pixel_source readyLatency 0
set_interface_property pixel_source ENABLED true
set_interface_property pixel_source EXPORT_OF ""
set_interface_property pixel_source PORT_NAME_MAP ""
set_interface_property pixel_source CMSIS_SVD_VARIABLES ""
set_interface_property pixel_source SVD_ADDRESS_GROUP ""

add_interface_port pixel_source out_data data Output 17
add_interface_port pixel_source out_valid valid Output 1

