# TCL File Generated by Component Editor 18.1
# Sun Dec 27 18:33:54 PST 2020
# DO NOT MODIFY


# 
# min_dist_finder "min_dist_finder" v1.0
#  2020.12.27.18:33:54
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module min_dist_finder
# 
set_module_property DESCRIPTION ""
set_module_property NAME min_dist_finder
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME min_dist_finder
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL min_dist_finder
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file min_dist_finder.sv SYSTEM_VERILOG PATH block_matching/min_dist_finder.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL min_dist_finder
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file min_dist_finder.sv SYSTEM_VERILOG PATH block_matching/min_dist_finder.sv


# 
# parameters
# 
add_parameter blk_h INTEGER 16
set_parameter_property blk_h DEFAULT_VALUE 16
set_parameter_property blk_h DISPLAY_NAME blk_h
set_parameter_property blk_h TYPE INTEGER
set_parameter_property blk_h UNITS None
set_parameter_property blk_h ALLOWED_RANGES -2147483648:2147483647
set_parameter_property blk_h HDL_PARAMETER true
add_parameter blk_w INTEGER 16
set_parameter_property blk_w DEFAULT_VALUE 16
set_parameter_property blk_w DISPLAY_NAME blk_w
set_parameter_property blk_w TYPE INTEGER
set_parameter_property blk_w UNITS None
set_parameter_property blk_w HDL_PARAMETER true
add_parameter search_blk_w INTEGER 64
set_parameter_property search_blk_w DEFAULT_VALUE 64
set_parameter_property search_blk_w DISPLAY_NAME search_blk_w
set_parameter_property search_blk_w TYPE INTEGER
set_parameter_property search_blk_w UNITS None
set_parameter_property search_blk_w ALLOWED_RANGES -2147483648:2147483647
set_parameter_property search_blk_w HDL_PARAMETER true
add_parameter search_blk_h INTEGER 16
set_parameter_property search_blk_h DEFAULT_VALUE 16
set_parameter_property search_blk_h DISPLAY_NAME search_blk_h
set_parameter_property search_blk_h TYPE INTEGER
set_parameter_property search_blk_h UNITS None
set_parameter_property search_blk_h ALLOWED_RANGES -2147483648:2147483647
set_parameter_property search_blk_h HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point out_conduit
# 
add_interface out_conduit conduit end
set_interface_property out_conduit associatedClock clock
set_interface_property out_conduit associatedReset reset
set_interface_property out_conduit ENABLED true
set_interface_property out_conduit EXPORT_OF ""
set_interface_property out_conduit PORT_NAME_MAP ""
set_interface_property out_conduit CMSIS_SVD_VARIABLES ""
set_interface_property out_conduit SVD_ADDRESS_GROUP ""

add_interface_port out_conduit min_blk_index_o blk_index Output 16
add_interface_port out_conduit min_sum sum Output 8
add_interface_port out_conduit min_sumh data Output 8
add_interface_port out_conduit average_sum average_sum Output 8


# 
# connection point in_conduit
# 
add_interface in_conduit conduit end
set_interface_property in_conduit associatedClock clock
set_interface_property in_conduit associatedReset reset
set_interface_property in_conduit ENABLED true
set_interface_property in_conduit EXPORT_OF ""
set_interface_property in_conduit PORT_NAME_MAP ""
set_interface_property in_conduit CMSIS_SVD_VARIABLES ""
set_interface_property in_conduit SVD_ADDRESS_GROUP ""

add_interface_port in_conduit sum sum Input 8
add_interface_port in_conduit out_coords blk_coords Input 16
add_interface_port in_conduit sum_valid valid Input 1
add_interface_port in_conduit blk_index_o blk_index Input 16


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 16
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source min_sum_valid valid Output 1
add_interface_port avalon_streaming_source min_out_coords data Output 16

