# TCL File Generated by Component Editor 18.1
# Sun Feb 23 16:54:24 PST 2020
# DO NOT MODIFY


# 
# ddr3_writer_gray_in "ddr3_writer_gray_in" v1.0
#  2020.02.23.16:54:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ddr3_writer_gray_in
# 
set_module_property DESCRIPTION ""
set_module_property NAME ddr3_writer_gray_in
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ddr3_writer_gray_in
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ddr3_writer_gray_in
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ddr3_writer_gray_in.sv SYSTEM_VERILOG PATH gray_in/ddr3_writer_gray_in.sv TOP_LEVEL_FILE
add_fileset_file ddr3_writer_fifo.v VERILOG PATH gray_in/ddr3_writer_fifo.v


# 
# parameters
# 
add_parameter in_width INTEGER 16
set_parameter_property in_width DEFAULT_VALUE 16
set_parameter_property in_width DISPLAY_NAME in_width
set_parameter_property in_width TYPE INTEGER
set_parameter_property in_width ENABLED false
set_parameter_property in_width UNITS None
set_parameter_property in_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property in_width HDL_PARAMETER true
add_parameter rotate_buffers INTEGER 0
set_parameter_property rotate_buffers DEFAULT_VALUE 0
set_parameter_property rotate_buffers DISPLAY_NAME rotate_buffers
set_parameter_property rotate_buffers TYPE INTEGER
set_parameter_property rotate_buffers UNITS None
set_parameter_property rotate_buffers ALLOWED_RANGES -2147483648:2147483647
set_parameter_property rotate_buffers HDL_PARAMETER true
add_parameter burst_len INTEGER 8
set_parameter_property burst_len DEFAULT_VALUE 8
set_parameter_property burst_len DISPLAY_NAME burst_len
set_parameter_property burst_len TYPE INTEGER
set_parameter_property burst_len UNITS None
set_parameter_property burst_len HDL_PARAMETER true


# 
# display items
# 


# 
# connection point start_1
# 
add_interface start_1 conduit end
set_interface_property start_1 associatedClock ddr3clk_sink
set_interface_property start_1 associatedReset ddr3clk_reset_sink
set_interface_property start_1 ENABLED true
set_interface_property start_1 EXPORT_OF ""
set_interface_property start_1 PORT_NAME_MAP ""
set_interface_property start_1 CMSIS_SVD_VARIABLES ""
set_interface_property start_1 SVD_ADDRESS_GROUP ""

add_interface_port start_1 start_address_i address Input 32


# 
# connection point ddr3_write_master
# 
add_interface ddr3_write_master avalon start
set_interface_property ddr3_write_master addressUnits WORDS
set_interface_property ddr3_write_master associatedClock ddr3clk_sink
set_interface_property ddr3_write_master associatedReset ddr3clk_reset_sink
set_interface_property ddr3_write_master bitsPerSymbol 8
set_interface_property ddr3_write_master burstOnBurstBoundariesOnly false
set_interface_property ddr3_write_master burstcountUnits WORDS
set_interface_property ddr3_write_master doStreamReads false
set_interface_property ddr3_write_master doStreamWrites false
set_interface_property ddr3_write_master holdTime 0
set_interface_property ddr3_write_master linewrapBursts false
set_interface_property ddr3_write_master maximumPendingReadTransactions 0
set_interface_property ddr3_write_master maximumPendingWriteTransactions 0
set_interface_property ddr3_write_master readLatency 0
set_interface_property ddr3_write_master readWaitTime 1
set_interface_property ddr3_write_master setupTime 0
set_interface_property ddr3_write_master timingUnits Cycles
set_interface_property ddr3_write_master writeWaitTime 0
set_interface_property ddr3_write_master ENABLED true
set_interface_property ddr3_write_master EXPORT_OF ""
set_interface_property ddr3_write_master PORT_NAME_MAP ""
set_interface_property ddr3_write_master CMSIS_SVD_VARIABLES ""
set_interface_property ddr3_write_master SVD_ADDRESS_GROUP ""

add_interface_port ddr3_write_master ddr3_write_address address Output 27
add_interface_port ddr3_write_master ddr3_write_data writedata Output 256
add_interface_port ddr3_write_master ddr3_write write Output 1
add_interface_port ddr3_write_master ddr3_waitrequest waitrequest Input 1
add_interface_port ddr3_write_master ddr3_burstcount burstcount Output 4


# 
# connection point ddr3clk_sink
# 
add_interface ddr3clk_sink clock end
set_interface_property ddr3clk_sink clockRate 0
set_interface_property ddr3clk_sink ENABLED true
set_interface_property ddr3clk_sink EXPORT_OF ""
set_interface_property ddr3clk_sink PORT_NAME_MAP ""
set_interface_property ddr3clk_sink CMSIS_SVD_VARIABLES ""
set_interface_property ddr3clk_sink SVD_ADDRESS_GROUP ""

add_interface_port ddr3clk_sink ddr3_clk clk Input 1


# 
# connection point pclk_sink
# 
add_interface pclk_sink clock end
set_interface_property pclk_sink clockRate 0
set_interface_property pclk_sink ENABLED true
set_interface_property pclk_sink EXPORT_OF ""
set_interface_property pclk_sink PORT_NAME_MAP ""
set_interface_property pclk_sink CMSIS_SVD_VARIABLES ""
set_interface_property pclk_sink SVD_ADDRESS_GROUP ""

add_interface_port pclk_sink pclk clk Input 1


# 
# connection point ddr3clk_reset_sink
# 
add_interface ddr3clk_reset_sink reset end
set_interface_property ddr3clk_reset_sink associatedClock ddr3clk_sink
set_interface_property ddr3clk_reset_sink synchronousEdges DEASSERT
set_interface_property ddr3clk_reset_sink ENABLED true
set_interface_property ddr3clk_reset_sink EXPORT_OF ""
set_interface_property ddr3clk_reset_sink PORT_NAME_MAP ""
set_interface_property ddr3clk_reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property ddr3clk_reset_sink SVD_ADDRESS_GROUP ""

add_interface_port ddr3clk_reset_sink ddr3clk_reset reset Input 1


# 
# connection point pclk_reset_sink
# 
add_interface pclk_reset_sink reset end
set_interface_property pclk_reset_sink associatedClock pclk_sink
set_interface_property pclk_reset_sink synchronousEdges DEASSERT
set_interface_property pclk_reset_sink ENABLED true
set_interface_property pclk_reset_sink EXPORT_OF ""
set_interface_property pclk_reset_sink PORT_NAME_MAP ""
set_interface_property pclk_reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property pclk_reset_sink SVD_ADDRESS_GROUP ""

add_interface_port pclk_reset_sink pclk_reset reset Input 1


# 
# connection point pixel_data_sink
# 
add_interface pixel_data_sink avalon_streaming end
set_interface_property pixel_data_sink associatedClock pclk_sink
set_interface_property pixel_data_sink associatedReset pclk_reset_sink
set_interface_property pixel_data_sink dataBitsPerSymbol 17
set_interface_property pixel_data_sink errorDescriptor ""
set_interface_property pixel_data_sink firstSymbolInHighOrderBits true
set_interface_property pixel_data_sink maxChannel 0
set_interface_property pixel_data_sink readyLatency 0
set_interface_property pixel_data_sink ENABLED true
set_interface_property pixel_data_sink EXPORT_OF ""
set_interface_property pixel_data_sink PORT_NAME_MAP ""
set_interface_property pixel_data_sink CMSIS_SVD_VARIABLES ""
set_interface_property pixel_data_sink SVD_ADDRESS_GROUP ""

add_interface_port pixel_data_sink pixel_data data Input 17
add_interface_port pixel_data_sink pixel_valid valid Input 1


# 
# connection point fifo_almost_full_conduit
# 
add_interface fifo_almost_full_conduit conduit end
set_interface_property fifo_almost_full_conduit associatedClock pclk_sink
set_interface_property fifo_almost_full_conduit associatedReset pclk_reset_sink
set_interface_property fifo_almost_full_conduit ENABLED true
set_interface_property fifo_almost_full_conduit EXPORT_OF ""
set_interface_property fifo_almost_full_conduit PORT_NAME_MAP ""
set_interface_property fifo_almost_full_conduit CMSIS_SVD_VARIABLES ""
set_interface_property fifo_almost_full_conduit SVD_ADDRESS_GROUP ""

add_interface_port fifo_almost_full_conduit fifo_almost_full fifo_almost_full Output 1


# 
# connection point pointer_src
# 
add_interface pointer_src avalon_streaming start
set_interface_property pointer_src associatedClock ddr3clk_sink
set_interface_property pointer_src associatedReset ddr3clk_reset_sink
set_interface_property pointer_src dataBitsPerSymbol 2
set_interface_property pointer_src errorDescriptor ""
set_interface_property pointer_src firstSymbolInHighOrderBits true
set_interface_property pointer_src maxChannel 0
set_interface_property pointer_src readyLatency 0
set_interface_property pointer_src ENABLED true
set_interface_property pointer_src EXPORT_OF ""
set_interface_property pointer_src PORT_NAME_MAP ""
set_interface_property pointer_src CMSIS_SVD_VARIABLES ""
set_interface_property pointer_src SVD_ADDRESS_GROUP ""

add_interface_port pointer_src pointer_data data Output 2
add_interface_port pointer_src pointer_valid valid Output 1

